/* eslint-disable */
// @ts-nocheck
// biome-ignore-all format: auto-generated file
// biome-ignore-all lint: auto-generated file

// This file is auto-generated by the flowbite-react CLI.
// Do not edit this file directly.
// Instead, edit the .flowbite-react/config.json file.

import type { StoreProps } from "flowbite-react/store";
import { StoreInit } from "flowbite-react/store/init";
import React from "react";

const config: StoreProps = {
  dark: true,
  prefix: "",
  version: 3,
};

export function ThemeInit() {
  return <StoreInit {...config} />;
}

ThemeInit.displayName = "ThemeInit";
