name: Setup
description: Setup Bun, Node and install packages

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.3.8

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Install packages
      shell: bash
      run: bun install
