export { card } from './skeleton.card';
export { circular } from './skeleton.circular';
export { image } from './skeleton.image';
export { list } from './skeleton.list';
export { rectangular } from './skeleton.rectangular';
export { rounded } from './skeleton.rounded';
export { root } from './skeleton.root';
export { testimonial } from './skeleton.testimonial';
export { video } from './skeleton.video';
