import type { FlowbiteSpinnerTheme } from './Spinner';

export const spinnerTheme: FlowbiteSpinnerTheme = {
  base: 'inline animate-spin text-gray-200',
  color: {
    blue: 'fill-blue-600',
    cyan: 'fill-cyan-600',
    dark: 'fill-gray-600',
    gray: 'fill-gray-600',
    green: 'fill-green-600',
    indigo: 'fill-indigo-600',
    light: 'fill-gray-600',
    lime: 'fill-lime-600',
    pink: 'fill-pink-600',
    purple: 'fill-purple-600',
    red: 'fill-red-600',
    teal: 'fill-teal-600',
    yellow: 'fill-yellow-400',
    info: 'fill-cyan-600',
    failure: 'fill-red-600',
    success: 'fill-green-500',
    warning: 'fill-yellow-400',
  },
  light: {
    off: {
      base: 'dark:text-gray-600',
      color: {
        blue: '',
        cyan: '',
        dark: 'dark:fill-gray-300',
        gray: 'dark:fill-gray-300',
        green: '',
        indigo: '',
        light: '',
        lime: '',
        pink: '',
        purple: '',
        red: '',
        teal: '',
        yellow: '',
        info: '',
        failure: '',
        success: '',
        warning: '',
      },
    },
    on: {
      base: '',
      color: {
        blue: '',
        cyan: '',
        dark: '',
        gray: '',
        green: '',
        indigo: '',
        light: '',
        lime: '',
        pink: '',
        purple: '',
        red: '',
        teal: '',
        yellow: '',
        info: '',
        failure: '',
        success: '',
        warning: '',
      },
    },
  },
  size: {
    xs: 'w-3 h-3',
    sm: 'w-4 h-4',
    md: 'w-6 h-6',
    lg: 'w-8 h-8',
    xl: 'w-10 h-10',
  },
};
