import { createTheme } from "../../helpers/create-theme";
import type { FlowbiteProgressTheme } from "./Progress";

export const progressTheme: FlowbiteProgressTheme = createTheme({
  base: "w-full overflow-hidden rounded-full bg-gray-200 dark:bg-gray-700",
  label: "mb-1 flex justify-between font-medium dark:text-white",
  bar: "space-x-2 rounded-full text-center font-medium leading-none text-cyan-300 dark:text-cyan-100",
  color: {
    dark: "bg-gray-600 dark:bg-gray-300",
    blue: "bg-blue-600",
    red: "bg-red-600 dark:bg-red-500",
    green: "bg-green-600 dark:bg-green-500",
    yellow: "bg-yellow-400",
    indigo: "bg-indigo-600 dark:bg-indigo-500",
    purple: "bg-purple-600 dark:bg-purple-500",
    cyan: "bg-cyan-600",
    gray: "bg-gray-500",
    lime: "bg-lime-600",
    pink: "bg-pink-500",
    teal: "bg-teal-600",
  },
  size: {
    sm: "h-1.5",
    md: "h-2.5",
    lg: "h-4",
    xl: "h-6",
  },
  circular: {
    base: "relative size-40",
    bar: "size-full -rotate-90",
    color: {
      barColor: {
        dark: "stroke-current text-gray-600 dark:text-gray-300",
        blue: "stroke-current text-blue-600",
        red: "stroke-current text-red-600 dark:text-red-500",
        green: "stroke-current text-green-600 dark:text-green-500",
        yellow: "stroke-current text-yellow-400",
        indigo: "stroke-current text-indigo-600 dark:text-indigo-500",
        purple: "stroke-current text-purple-600 dark:text-purple-500",
        cyan: "stroke-current text-cyan-600",
        gray: "stroke-current text-gray-500",
        lime: "stroke-current text-lime-600",
        pink: "stroke-current text-pink-500",
        teal: "stroke-current text-teal-600",
      },
      bgColor: "stroke-current text-gray-200 dark:text-neutral-700",
    },
    label: {
      base: "absolute start-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 transform",
      text: "text-center text-2xl font-bold",
      textColor: {
        dark: "text-gray-600 dark:text-gray-300",
        blue: "text-blue-600",
        red: "text-red-600 dark:text-red-500",
        green: "text-green-600 dark:text-green-500",
        yellow: "text-yellow-400",
        indigo: "text-indigo-600 dark:text-indigo-500",
        purple: "text-purple-600 dark:text-purple-500",
        cyan: "text-cyan-600",
        gray: "text-gray-500",
        lime: "text-lime-600",
        pink: "text-pink-500",
        teal: "text-teal-600",
      },
    },
  },
});
