export { controls } from './carousel.controls';
export { events } from './carousel.events';
export { indicators } from './carousel.indicators';
export { pauseOnHover } from './carousel.pauseOnHover';
export { root } from './carousel.root';
export { slide } from './carousel.slide';
export { slideInterval } from './carousel.slideInterval';
export { sliderContent } from './carousel.sliderContent';
export { autoHideControls } from './carousel.autoHideControls';
