import fs from "fs/promises";
import { initFilePath } from "../consts";
import type { Config } from "./setup-config";

/**
 * Sets up the `.flowbite-react/init.tsx` file in the project.
 *
 * This function ensures the init.tsx file exists and is up-to-date with the current configuration.
 * It will create or update the file if needed.
 */
export async function setupInit(config: Config) {
  const content = `
/* eslint-disable */
// @ts-nocheck
// biome-ignore-all format: auto-generated file
// biome-ignore-all lint: auto-generated file

// This file is auto-generated by the flowbite-react CLI.
// Do not edit this file directly.
// Instead, edit the .flowbite-react/config.json file.

import type { StoreProps } from "flowbite-react/store";
import { StoreInit } from "flowbite-react/store/init";
import React from "react";

const config: StoreProps = {
  dark: ${config.dark},
  prefix: "${config.prefix}",
  version: ${config.version},
};

export function ThemeInit() {
  return <StoreInit {...config} />;
}

ThemeInit.displayName = "ThemeInit";
`.trim();

  try {
    let currentContent: string;
    try {
      currentContent = await fs.readFile(initFilePath, "utf-8");
    } catch {
      currentContent = "";
    }

    if (currentContent.trimEnd() !== content) {
      console.log(`${currentContent ? "Updating" : "Creating"} ${initFilePath} file...`);
      setTimeout(() => fs.writeFile(initFilePath, content), 10);
    }
  } catch (error) {
    console.error(`Failed to update ${initFilePath}:`, error);
  }
}
